/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Cuenta;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos Sarmientos
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Cuenta c;
    long num_cuenta, id_cliente;
    double saldo_actual;
    
    public Principal() {
        initComponents();
        cmdCrearCuenta.setEnabled(true);
        cmdIngresar.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdActualizar.setEnabled(false);
        cmdRetirar.setEnabled(false);
        cmdLimpiar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        cmdLimpiar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumCuenta = new javax.swing.JTextField();
        txtIdCliente = new javax.swing.JTextField();
        txtSaldoActual = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cmdCrearCuenta = new javax.swing.JButton();
        cmdIngresar = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdRetirar = new javax.swing.JButton();
        cmdActualizar = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDatos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Cuenta Bancaria");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la cuenta\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdLimpiar1.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        cmdLimpiar1.setText("Limpiar");
        cmdLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiar1ActionPerformed(evt);
            }
        });
        jPanel4.add(cmdLimpiar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 150, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Num. Cuenta:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("ID Cliente:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Saldo Actual:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtNumCuenta.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txtNumCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumCuentaKeyTyped(evt);
            }
        });
        jPanel4.add(txtNumCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 120, 30));

        txtIdCliente.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txtIdCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdClienteKeyTyped(evt);
            }
        });
        jPanel4.add(txtIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 120, 30));

        txtSaldoActual.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txtSaldoActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoActualKeyTyped(evt);
            }
        });
        jPanel4.add(txtSaldoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 120, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 270, 170));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrearCuenta.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdCrearCuenta.setText("Crear cuenta");
        cmdCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearCuentaActionPerformed(evt);
            }
        });
        jPanel2.add(cmdCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 160, -1));

        cmdIngresar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdIngresar.setText("Ingresar");
        cmdIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 160, -1));

        cmdMostrar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, -1));

        cmdRetirar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdRetirar.setText("Retirar");
        cmdRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRetirarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 160, -1));

        cmdActualizar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdActualizar.setText("Actualizar Saldo");
        cmdActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 160, -1));

        cmdLimpiar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 160, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 190, 220));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDatos.setEditable(false);
        txtDatos.setColumns(20);
        txtDatos.setRows(5);
        jScrollPane1.setViewportView(txtDatos);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 240, 80));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 280, 120));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiar1ActionPerformed
        
    }//GEN-LAST:event_cmdLimpiar1ActionPerformed

    private void txtNumCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumCuentaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNumCuentaKeyTyped

    private void txtIdClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdClienteKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtIdClienteKeyTyped

    private void txtSaldoActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoActualKeyTyped
        char c = evt.getKeyChar();
        if ((!Character.isDigit(c)) && (evt.getKeyChar() != '.')) {
            getToolkit().beep();
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtSaldoActual.getText().contains(".")) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtSaldoActualKeyTyped

    private void cmdCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearCuentaActionPerformed
        if (txtNumCuenta.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Número de cuenta", "error", JOptionPane.ERROR_MESSAGE);
            txtNumCuenta.requestFocusInWindow();
        } else if (Long.parseLong(txtNumCuenta.getText().trim()) == 0) {
            JOptionPane.showMessageDialog(this, "El número de cuenta no puede ser 0", "error", JOptionPane.ERROR_MESSAGE);
            txtNumCuenta.requestFocusInWindow();
            txtNumCuenta.selectAll();
        } else if (txtIdCliente.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Número de identificación del cliente", "error", JOptionPane.ERROR_MESSAGE);
            txtIdCliente.requestFocusInWindow();
        } else if (Long.parseLong(txtIdCliente.getText().trim()) == 0) {
            JOptionPane.showMessageDialog(this, "El número de Identificación del cliente no puede ser cero", "error", JOptionPane.ERROR_MESSAGE);
            txtIdCliente.requestFocusInWindow();
            txtIdCliente.selectAll();
        } else if (txtSaldoActual.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Saldo Actual de la cuenta", "error", JOptionPane.ERROR_MESSAGE);
            txtSaldoActual.requestFocusInWindow();
        } else if (Integer.parseInt(txtSaldoActual.getText().trim()) == 0) {
            JOptionPane.showMessageDialog(this, "el saldo actual no puede ser cero", "error", JOptionPane.ERROR_MESSAGE);
            txtSaldoActual.requestFocusInWindow();
            txtSaldoActual.selectAll();
        } else {

            num_cuenta = Long.parseLong(txtNumCuenta.getText());
            id_cliente = Long.parseLong(txtIdCliente.getText());
            saldo_actual = Double.parseDouble(txtSaldoActual.getText());
            c = new Cuenta(num_cuenta, id_cliente, saldo_actual);
            JOptionPane.showMessageDialog(this, "Cuenta guardada exitosamente");
            txtNumCuenta.setEditable(false);
            txtIdCliente.setEditable(false);
            txtSaldoActual.setEditable(false);
            cmdCrearCuenta.setEnabled(false);
            cmdIngresar.setEnabled(true);
            cmdMostrar.setEnabled(true);
            cmdActualizar.setEnabled(true);
            cmdRetirar.setEnabled(true);
            cmdLimpiar.setEnabled(true);
        }
    }//GEN-LAST:event_cmdCrearCuentaActionPerformed

    private void cmdIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresarActionPerformed
        double ingreso;
        int sw = 0;
        do {
            try {
                ingreso = Double.parseDouble(JOptionPane.showInputDialog(this, "Digite Cantidad a ingresar"));
                if (ingreso < 1) {
                    JOptionPane.showMessageDialog(this, "digite un numero valido", "Error", JOptionPane.ERROR_MESSAGE);
                    sw = 0;
                } else {
                    c.ingresar(ingreso);
                    sw = 1;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "digite un numero valido", "Error", JOptionPane.ERROR_MESSAGE);
                sw = 0;
            } catch (NullPointerException e) {
                int res = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas salir?", "Salir", JOptionPane.YES_NO_OPTION);
                if (res == 0) {
                    sw = 1;
                } else {
                    sw = 0;
                }
            }
        } while (sw == 0);
    }//GEN-LAST:event_cmdIngresarActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        String aux;
        aux = c.mostrar();
        txtDatos.setText(aux);
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRetirarActionPerformed
        double egreso;
        int sw = 0;
        do {
            try {
                egreso = Double.parseDouble(JOptionPane.showInputDialog(this, "Digite Cantidad a retirar"));
                if (c.getSaldo_actual() < egreso) {
                    JOptionPane.showMessageDialog(this, "La cantidad de dinero a retirar es mayor \n"
                        + "que la cantidad de dinero actual");
                    sw = 0;
                } else if (egreso < 0) {
                    JOptionPane.showMessageDialog(this, "digite un numero valido", "Error", JOptionPane.ERROR_MESSAGE);
                    sw = 0;
                } else {
                    c.retirar(egreso);
                    sw = 1;
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "digite un numero valido", "Error", JOptionPane.ERROR_MESSAGE);
                sw = 0;
            } catch (NullPointerException e) {
                int res = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas salir?", "Salir", JOptionPane.YES_NO_OPTION);
                if (res == 0) {
                    sw = 1;
                } else {
                    sw = 0;
                }
            }
        } while (sw == 0);

    }//GEN-LAST:event_cmdRetirarActionPerformed

    private void cmdActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdActualizarActionPerformed
        double interes;
        int sw = 0;
        do {
            try {
                interes = Double.parseDouble(JOptionPane.showInputDialog(this, "Digite interes anual"));
                if (interes < 0) {
                    JOptionPane.showMessageDialog(this, "digite un numero valido", "Error", JOptionPane.ERROR_MESSAGE);
                    sw = 0;
                } else {
                    c.actualizarsaldo(interes);
                    sw = 1;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "digite un numero valido", "Error", JOptionPane.ERROR_MESSAGE);
                sw = 0;
            } catch (NullPointerException e) {
                int res = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas salir?", "Salir", JOptionPane.YES_NO_OPTION);
                if (res == 0) {
                    sw = 1;
                } else {
                    sw = 0;
                }
            }
        } while (sw == 0);
    }//GEN-LAST:event_cmdActualizarActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        txtNumCuenta.setText("");
        txtIdCliente.setText("");
        txtSaldoActual.setText("");
        txtDatos.setText("");
        txtNumCuenta.setEditable(true);
        txtIdCliente.setEditable(true);
        txtSaldoActual.setEditable(true);
        cmdCrearCuenta.setEnabled(true);
        cmdIngresar.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdActualizar.setEnabled(false);
        cmdRetirar.setEnabled(false);
        cmdLimpiar.setEnabled(true);
        txtNumCuenta.requestFocusInWindow();
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdActualizar;
    private javax.swing.JButton cmdCrearCuenta;
    private javax.swing.JButton cmdIngresar;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdLimpiar1;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdRetirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDatos;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtNumCuenta;
    private javax.swing.JTextField txtSaldoActual;
    // End of variables declaration//GEN-END:variables
}
